@startuml
title  Digitize Immunization Event (Online)

hide footbox

!include ./style.iuml

actor "Subject of Care" as SOC
actor "DDCC Holder" as Holder
actor "Vaccinator" as Vaxer
actor "Data Entry Personnel" as DEP
Participant "Paper\nRegistry" as PaperReg
Participant "Digital\nHealth\nSolution" as DHS
Participant "DDCC:VS\nGeneration\nService" as CertGen
Participant "Shared\nHealth\nRecord" as SHR
Participant "DDCC:VS\nRegistry\nService" as DDCCReg
Participant "DDCC:VS\nRepository\nService" as DDCCRepo




autonumber 1.1.1

   activate Holder
   activate SOC
   activate Vaxer

    alt Subject of Care has an DDCC Card
      Holder->Vaxer: Give Subject of Care's\nPaper DDCC to Vaccinator
    else Subject of Care needs an DDCC Card
      Vaxer->Holder: Give DDCC Holder new\nDDCC Card	
    end
   
    Vaxer->SOC : Vaccinate


    Vaxer->Holder:  record immunization event\nin Paper DDCC 
    Vaxer->DHS: record immunization\nevent details
    DHS->CertGen: send immunization\nevent details
    CertGen->CertGen: Generate DDCC\nDocument
    opt Generate 2D Barcode
      CertGen->CertGen: Generate 2D Barcode
      CertGen->CertGen: Add 2D Barcode to\nDDCC Document
    end
    CertGen->CertGen: Sign DDCC Document
    opt Has DDCC:VS Registry
	 opt Has DDCC:VS Repository
	   CertGen->DDCCRepo: upload DDCC Document
	 end
   	 CertGen->DDCCReg: upload DDCC Bundle
    end
    CertGen->DHS: return signed\nDDCC Document

    DHS->DHS: store signed DDCC\nDocument in\nSubect of Care's record

    opt Can Print QR Stickers
         Vaxer->Vaxer: Print QR code sticker\nfrom signed DDCC Document
 	 Vaxer->Holder: Place QR code\nsticker on DDCC
    end	


   deactivate Holder
   deactivate SOC
   deactivate Vaxer
   

   opt  Has Shared Health Record
	DHS->SHR: upload IPS Bundle
   end


@enduml


