@startuml
title  Digitize Immunization Event (Online)

hide footbox

!include ./style.iuml

actor "Subject of Care" as SOC
actor "DDCC Holder" as Holder
actor "Vaccinator" as Vaxer
actor "Data Entry Personnel" as DEP
Participant "Digital Health Solution" as DHS
Participant "Paper\nRegistry" as PaperReg
Participant "DDCC Certificate\nGenerator" as CertGen
Participant "Shared Health\nRecord" as SHR
Participant "DDCC\nRegistry" as DDCCReg

autonumber 1.1.1

   activate Holder
   activate SOC
   activate Vaxer

    alt Subject of Care has an DDCC Card
      Holder->Vaxer: Give Subject of Care's\nPaper DDCC to Vaccinator
    else Subject of Care needs an DDCC Card
      Vaxer->Holder: Give DDCC Holder new\nDDCC Card	
    end
   
    Vaxer->SOC : Vaccinate


    Vaxer->Holder:  record immunization event\nin Paper DDCC 
    Vaxer->DHS: record immunization\nevent details
    DHS->CertGen: send immunization event\ndetails as unsigned\nQR UVCEI
    CertGen->DHS: return signed QR UVCEI
    DHS->DHS: store QR UVCEI in\nSubect of Care's record
    opt Can Print QR Stickers
         Vaxer->Vaxer: Print QR code sticker\nfrom signed UVCEI
 	 Vaxer->Holder: Place QR code\nsticker on DDCC
    end	


   deactivate Holder
   deactivate SOC
   deactivate Vaxer


   

   alt  Has Shared Health Record
	DHS->SHR: upload IPS Bundle
	SHR->SHR: $transform IPS Bundle to DDCC Bundle
	SHR->DDCCReg: upload DDCC Bundle
   else Has DDCC Registry
   	DHS->DDCCReg: upload DDCC Bundle
   end


@enduml


