@startuml
title Transaction: Print Paper DDCC

hide footbox

!include ./style.iuml

actor "Public\nHealth\nAuthority" as PHA
Participant "Verifier" 
Participant "DDCC\nRegistry" as DDCCReg

autonumber 1.1.1

PHA->PHA : generate a new pair of DDCC document identifiers (Bundle,Composition)
PHA->DDCCReg : register new DDCC identifiers\non internal list of reserved\nidentifiers
opt Validate Composition Identifier
   Verifier -> DDCCReg: request current\nDigital DDCC with a given\nComposition identifier
   DDCCReg->DDCCReg: search list of reserved\nidentifiers for the requested\nComposition identifier
   alt Composition Identifier Found
       DDCCReg->Verifier: Return (empty) DDCC document bundle
   else Composition Identifier Not Found
       DDCCReg->Verifier: Return error condition
   end
end 

@enduml

