@startuml
title Transaction: Register Health Certificate

hide footbox

!include ./style.iuml

Participant "SHC Generator"  as SHCGen
Participant "SHC\nRegistry\nService" as SHCReg

autonumber 1.1.1

SHCGen->SHCReg: Register Health Certificate Request
SHCGen->SHCReg: Register Health Certificate Response

@enduml

