@startuml
title Transaction: Register Health Certificate

hide footbox

!include ./style.iuml

Participant "DDCC:VS\nGeneration\nService"  as DDCCGen
Participant "DDCC:VS\nRegistry\nService" as DDCCReg

autonumber 1.1.1

DDCCGen->DDCCReg: Register Health Certificate Request
DDCCReg->DDCCGen: Register Health Certificate Response

@enduml

