@startuml
title Transaction: Request Smart Health Certificate

hide footbox

!include ./style.iuml

actor "Public\nHealth\nAuthority" as PHA
Participant "Verifier" 
Participant "SHC\nRegistry\nSerice" as SHCReg

autonumber 1.1.1

Verifier -> SHCReg: request current Digital SHC with a given Composition identifier
SHCReg->SHCReg: search list of reserved\nidentifiers for the requested\ncomposition identifier
    alt Composition Identifier Found
    	SHCReg->Verifier: Return SHC document bundle
    else Composition Identifier Not Found
     	 SHCReg->Verifier: Return error condition
    end

@enduml


