@startuml
title Transaction: Retrieve Health Certificate

hide footbox

!include ./style.iuml

Participant "Point of Care"  as POC
Participant "Verifier"
Participant "DDCC\nRegistry\nService" as DDCCReg

autonumber 1.1.1

alt Point of Care
    POC->DDCCReg: Retrieve Health Certificate Request
    DDCCReg->POC: Retrieve Health Certificate Response
else Verifier
    Verifier->DDCCReg: Retrieve Health Certificate Request
    DDCCReg->Verifier: Retrieve Health Certificate Response
end

@enduml

