@startuml
title Transaction: Retrieve Health Certificate Reference

hide footbox

!include ./style.iuml

Participant "Verifier"
Participant "DDCC:VS\nRegistry\nService" as DDCCReg

autonumber 1.1.1

Verifier->DDCCReg: Retrieve Health Certificate Reference Request
DDCCReg->Verifier: Retrieve Health Certificate Reference Response

@enduml

