@startuml
title Transaction: Retrieve Health Folder

hide footbox

!include ./style.iuml

Participant "Point of Care"  as POC
Participant "Verifier"
Participant "DDCC\nRegistry\nService" as DDCCReg

autonumber 1.1.1

alt Point of Care
    POC->DDCCReg: Retrieve Health Folder Request
    DDCCReg->POC: Retrieve Health Folder Response
else Verifier
    Verifier->DDCCReg: Retrieve Health Folder Request
    DDCCReg->Verifier: Retrieve Health Folder Response
end

@enduml

