@startuml
title Transaction: Retrieve Health Certificate

hide footbox

!include ./style.iuml

Participant "Digital\nHealth\nSolution"  as DHS
Participant "Verifier"
Participant "DDCC:VS\nRepository\nService" as DDCCRepo

autonumber 1.1.1

alt Digital Health Solution
    DHS->DDCCRepo: Retrieve Health Certificate Request
    DDCCRepo->DHS: Retrieve Health Certificate Response
else Verifier
    Verifier->DDCCRepo: Retrieve Health Certificate Request
    DDCCRepo->Verifier: Retrieve Health Certificate Response
end

@enduml

