@startuml
title Transaction: Retrieve Health Certificate

hide footbox

!include ./style.iuml

Participant "Point of Care"  as POC
Participant "Verifier"
Participant "SHC\nRegistry\nService" as SHCReg

autonumber 1.1.1

alt Point of Care
    POC->SHCReg: Retrieve Health Certificate Request
    SHCReg->POC: Retrieve Health Certificate Response
else Verifier
    Verifier->SHCReg: Retrieve Health Certificate Request
    SHCReg->Verifier: Retrieve Health Certificate Response
end

@enduml

