@startuml
title Transaction: Retrieve Health Folder

hide footbox

!include ./style.iuml

Participant "Point of Care"  as POC
Participant "Verifier"
Participant "SHC\nRegistry\nService" as SHCReg

autonumber 1.1.1

alt Point of Care
    POC->SHCReg: Retrieve Health Folder Request
    SHCReg->POC: Retrieve Health Folder Response
else Verifier
    Verifier->SHCReg: Retrieve Health Folder Request
    SHCReg->Verifier: Retrieve Health Folder Response
end

@enduml

