@startuml
title Transaction: Store Health Certificate

hide footbox

!include ./style.iuml

Participant "DDCC:VS\nGeneration\nService"  as DDCCGen
Participant "DDCC:VS\nRepository\nService"  as DDCCRepo

autonumber 1.1.1

DDCCGen->DDCCRepo: Store Health Certificate Request
DDCCRepo->DDCCGen: Return Store Health Certificate Response

@enduml

