@startuml
title Transaction: Submit Health Event

hide footbox

!include ./style.iuml

actor "Point of Care" as POC
Participant "SHC Generator"  as SHCGen

autonumber 1.1.1

POC->SHCGen: Submit Health Event Request
SHCGen->POC: Return Submit Health Event Response

@enduml

