@startuml
skinparam svgDimensionStyle false

title DDCC Sequence Diagrams

actor "Vaccinated or\nTested Person" as VP
actor "DDCC Holder\n(usually Vaccinated \nor Tested Person)" as DH
actor "Health Worker\n or Data Entry \nPersonnel" as HW
actor "Verifier" as VER
participant "Digital Health\nSolution (DHS)\n(e.g. openSRP or an LIS)" as DHS
participant "DDCC Verifier\n Application" as VAP
participant "DDCC Generation\nService (e.g. DDCC\nTransactions Mediator)" as CGS

box "Public Health Authority (PHA)"

   participant "Public Key Infrastructure\n (PKI) Gateway\n(e.g. DGCG)" as GATE
   participant "Knowledge Repository\nFHIR Server" as KM
   participant "Data Store - Trusted FHIR Server\n(DDCC Registry Service\n& Repository Service)"  as SHR
end box

autonumber "<b>00:</b>"

group DDCC Certificate Generation
    GATE->CGS: Establish PKI trust network\n(unspecified, reference\nimplementation\nis DDCC Gateway)
  
    alt DDCC:VS Vaccination 

   	 HW->VP: Record Person demographic information
  note right: This is a simplified example.\nSee processes in DDCC:VS\nguidance document.
   	 HW->VP: Vaccinate client
     HW->DHS: Record vaccination event

    else DDCC:TR Test
     HW->DHS: Record core data set\ndata elements for a DDCC:TR
note left: Process starts after\na test report was generated.\nSee full list of pre-conditions\nfor a DDCC:TR in guidance document. 
    End
    
    DHS->CGS: DDCC: Submit Health Event /\nGenerate Health Certificate
    CGS->CGS: Ensure DHS has node level\nauthentication\nIHE: ATNA
    CGS->CGS: Log transaction / audit trail\nIHE: ATNA (RESTful?)
    CGS->CGS: FHIR: Create Bundle:\nDDCC Document
    opt store online content
         CGS->SHR: DDCC: Store Health Certificate\nFHIR: DDCC Document
    end
    CGS->SHR: DDCC: Register Health Certificate\nMHDS: ITI-65 Provide Document Bundle\nFHIR: create Bundle: \nSubmissionSet & DocumentReference



    CGS->DHS: DDCC: Generate Health Certificate response\nFHIR Bundle: DDCC Document
    DHS->DH: Share HCID and/or QR codes  (paper or wallet, unspecified)
end 

group DDCC:VS-Continuity of Care scenario
    HW->VP: Client registration
    DH->HW: Share QR code

    HW->DHS: Scan QR code
    DHS->DHS: Identify QR code type\nDeserialize
    opt  retrieve online content
        GATE->HW: Authenticate and authorize usage (unspecified, reference implementation is KeyCloak)
        DHS->SHR: DDCC: Retrieve Health Folder\nMHD: ITI-66 Find Document Lists\nFHIR: query List
        loop DocumentReference
           DHS->SHR: DDCC: Retrieve Health Certificate\nMHD: ITI-68 Retrieve Document\nFHIR: retrieve Bundle: DDCC Document
        end
    end
    HW->DHS: Review immunization history
    HW->VP: Determine if any actions\nare needed and provide care
end

group DDCC Certificate Verification & Validation

    opt refresh cache
        VAP->KM: Refresh FHIR ValueSet & Library resources (CQL/ELM) for validation business rules
	VAP->GATE: Refresh trust network public keys &\n document signer certificate revocation list
    end 

    DH->VER: Share QR code
    VER->VAP: Scan QR code
    VAP->VAP: Identify QR code type\nDeserialize

    opt  retrieve online content
        GATE->VER: Authenticate and authorize usage (unspecified, reference implementation is KeyCloak)
        alt Validate HCID/Folder
          VAP->SHR: DDCC: Retrieve Health Folder\nMHD: ITI-66 Find Document Lists\nFHIR: query List
          loop DocumentReference
            VAP->SHR: DDCC: Retrieve Health Certificate\nMHD: ITI-68 Retrieve Document\nFHIR: retrieve Bundle: DDCC Document
          end
        else Validate Document
          VAP->SHR: DDCC: Retrieve Health Certificate\nMHD: ITI-68 Retrieve Document\nFHIR: retrieve Bundle: DDCC Document
        end
    end

    VAP->VAP: Execute CQL/ELM validation\nstatus business rules\nagainst DDCC Document
    VER->VAP: Review validation status
    VER->DH: Indicate result\nof validation check
end


@enduml
