@startuml
skinparam svgDimensionStyle false

title DDCC Workflows



actor "Vaccinated\nPerson\n(Subject of Care)" as VP
actor "DDCC Holder" as DH
actor "Vaccinator\n (Health worker)" as HW
actor "Verifier" as VER
participant "Digital Health\nSolution\n(e.g. openSRP)" as DHS
participant "DDCC: Certificate\nGeneration Service\n(e.g. Reference App)" as CGS

box "Public Health Authortity"
   actor "Governance Actor" as GA

   participant "PKI Gateway\n(e.g. DDCCG)" as GATE
   participant "Knowledge Repo\nFHIR Server" as KM
   participant "Data Store\nTrusted FHIR Server\n(DDCC Regsistry Service\n& DDCC Repository Service)"  as SHR
end box

autonumber "<b>00:</b>"

group DDCC:VS-Vaccination & Certificate Generation
    GATE->CGS: Establish PKI trust network\n(unspecified, reference implementation\nis DDCC Gateway)
    HW->VP: Client registration
    HW->VP: Vaccinate client
    HW->DHS: Record vaccination event
    DHS->CGS: DDCC: Submit Health Event /\nGenerate Health Certificate

    CGS->CGS: Ensure Digital Health Solution has node level authentication\nIHE: ATNA
    CGS->CGS: Log transaction / audit trail\nIHE: ATNA (RESTful?)
    CGS->SHR: DDCC: Register Health Certificate\nMHDS: ITI-65\nFHIR: create Bundle: SubmissionSet & DocumentReference

    opt store online content
         CGS->SHR: DDCC: Store Health Certificate\nFHIR: Create Bundle: DDCC Document
    end

    CGS->DHS: DDCC: Generate Health Certificate response\nFHIR Bundle: DDCC Document
    DHS->DH: Share HCID and/or QR codes (paper or wallet, unspecified)
end 

group DDCC:VS-Contuinuty of Care
    HW->VP: Client registration
    DH->HW: Share QR code

    HW->DHS: Scan QR code
    DHS->DHS: Identify QR code type\nDeserialize\nMap to DDCC Document
    opt  retrieve online content
        GATE->HW: Authenticate and authorize usage (unspecified, reference implementation is KeyCloak)
        DHS->SHR: DDCC: Retrieve Health Folder\nMHD: ITI-66\nFHIR: query List
        loop DocumentReference
           DHS->SHR: DDCC: Retrieve Health Certificate\nMHD: ITI-68\nFHIR: retrieve Bundle: DDCC Document
           loop DocumentReference: retrieve QR-codes or PDFs
               DHS->SHR: DDCC: Retrieve Health Certificate Reference\nMHD: ITI-67\nFHIR: retrieve DocumentReference:\n attachments of pdf or image (e.g. png)
            end
        end
    end
    HW->DHS: Review immunization history
    HW->VP: Determine if any actions are needed and provide care
end

group Certificate Verification & Validation

    opt refresh cache
        DHS->KM: Refresh FHIR ValueSet & Library resources (CQL/ELM) for validation business rules
	DHS->GATE: Refresh trust network public keys & revoked key list
    end 

    DH->VER: Share QR code
    VER->DHS: Scan QR code
    DHS->DHS: Identify QR code type\nDeserialize\nMap to DDCC Document

    opt  retrieve online content
        GATE->VER: Authenticate and authorize usage (unspecified, reference implementation is KeyCloak)

        DHS->SHR: DDCC: Retrieve Health Folder\nMHD: ITI-66\nFHIR: query List
        loop DocumentReference
           DHS->SHR: DDCC: Retrieve Health Certificate\nMHD: ITI-68\nFHIR: retrieve Bundle: DDCC Document
        end
    end

    DHS->DHS: Exectute CQL/ELM validation status business rules\nagainst DDCC Document
    VER->DHS: Review validation status
    VER->DH: Indicate result of validation check
end

group DDCC Revocation
    opt Revocation of a PKI document signer certificate 
        GA->GATE: Add identified document signer\ncertificates to revoked key list\n[ADDITIONAL STEPS TO BE ADDED]
    end 
    
  opt Revocation of a DDCC:TR 
        
    end 
    
  
end



@enduml
