CodeSystem: WHO_DDCC_loinc
Title: "LOINC codes used in this IG"
Description: "All LOINC codes from `http://loinc.org` used in this IG. Provided so the FHIR server can perform expansions."
* ^experimental = true
* ^caseSensitive = true
* ^url = http://loinc.org

* #LP6464-4 "Nucliec acid amplification with probe detection"
* #LP217198-3 "Rapid immunoassay"
* #100861-4 "Cells.CD4+CD154+/CD4 cells in Blood --after stimulation with SARS-CoV-2 Nucleocapsid peptide"
* #100858-0 "Cells.CD4+CD154+/CD4 cells in Blood --after stimulation with SARS-CoV-2 Spike peptide"
* #100862-2 "Cells.CD4.Interferon gamma-expressing/CD4 cells in Blood --after stimulation with SARS-CoV-2 Nucleocapsid peptide"
* #100859-8 "Cells.CD4.Interferon gamma-expressing/CD4 cells in Blood --after stimulation with SARS-CoV-2 Spike peptide"
* #100863-0 "Cells.CD4.Tumor necrosis factor alfa-expressing/CD4 cells in Blood --after stimulation with SARS-CoV-2 Nucleocapsid peptide"
* #100860-6 "Cells.CD4.Tumor necrosis factor alfa-expressing/CD4 cells in Blood --after stimulation with SARS-CoV-2 Spike peptide"
* #96766-1 "GISAID sequence accession number"
* #95942-9 "Influenza virus A and B and SARS-CoV+SARS-CoV-2 (COVID-19) Ag panel - Upper respiratory specimen by Rapid immunoassay"
* #97099-6 "Influenza virus A and B and SARS-CoV-2 (COVID-19) Ag panel - Upper respiratory specimen by Rapid immunoassay"
* #95941-1 "Influenza virus A and B and SARS-CoV-2 (COVID-19) and Respiratory syncytial virus RNA panel - Respiratory specimen by NAA with probe detection"
* #95380-2 "Influenza virus A and B and SARS-CoV-2 (COVID-19) and SARS-related CoV RNA panel - Respiratory specimen by NAA with probe detection"
* #95423-0 "Influenza virus A and B and SARS-CoV-2 (COVID-19) identified in Respiratory specimen by NAA with probe detection"
* #95422-2 "Influenza virus A and B and SARS-CoV-2 (COVID-19) RNA panel - Respiratory specimen by NAA with probe detection"
* #100345-8 "Influenza virus A and B and SARS-CoV-2 (COVID-19) RNA panel - Specimen by NAA with probe detection"
* #98733-9 "Percent neutralization by SARS coronavirus 2 spike protein RBD neutralizing antibody in Serum or Plasma by Immunoassay"
* #99771-8 "SARS coronavirus 2 spike and nucleocapsid protein stimulated gamma interferon panel - Blood"
* #98846-9 "SARS coronavirus 2 stimulated gamma interferon release by Helper (CD4+) T-cells [Units/volume] corrected for background in Blood by Immunoassay"
* #98847-7 "SARS coronavirus 2 stimulated gamma interferon release by lymphocytes [Units/volume] corrected for background in Blood by Immunoassay"
* #99774-2 "SARS coronavirus 2 stimulated gamma interferon release by T-cells.Nucleocapsid Ag spot count [#] corrected for background in Blood"
* #99773-4 "SARS coronavirus 2 stimulated gamma interferon release by T-cells.Spike Ag spot count [#] corrected for background in Blood"
* #95209-3 "SARS-CoV+SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay"
* #94763-0 "SARS-CoV-2 (COVID-19) [Presence] in Specimen by Organism specific culture"
* #94661-6 "SARS-CoV-2 (COVID-19) Ab [Interpretation] in Serum or Plasma"
* #95825-6 "SARS-CoV-2 (COVID-19) Ab [Presence] in DBS by Immunoassay"
* #98069-8 "SARS-CoV-2 (COVID-19) Ab [Presence] in Saliva (oral fluid) by Rapid immunoassay"
* #94762-2 "SARS-CoV-2 (COVID-19) Ab [Presence] in Serum or Plasma by Immunoassay"
* #95542-7 "SARS-CoV-2 (COVID-19) Ab [Presence] in Serum, Plasma or Blood by Rapid immunoassay"
* #94769-7 "SARS-CoV-2 (COVID-19) Ab [Units/volume] in Serum or Plasma by Immunoassay"
* #96118-5 "SARS-CoV-2 (COVID-19) Ab panel - DBS by Immunoassay"
* #94504-8 "SARS-CoV-2 (COVID-19) Ab panel - Serum or Plasma by Immunoassay"
* #94503-0 "SARS-CoV-2 (COVID-19) Ab panel - Serum, Plasma or Blood by Rapid immunoassay"
* #94558-4 "SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay"
* #96119-3 "SARS-CoV-2 (COVID-19) Ag [Presence] in Upper respiratory specimen by Immunoassay"
* #97097-0 "SARS-CoV-2 (COVID-19) Ag [Presence] in Upper respiratory specimen by Rapid immunoassay"
* #96094-8 "SARS-CoV-2 (COVID-19) and SARS-related CoV RNA panel - Respiratory specimen by NAA with probe detection"
* #98080-5 "SARS-CoV-2 (COVID-19) and SARS-related CoV RNA panel - Saliva (oral fluid) by NAA with probe detection"
* #96896-6 "SARS-CoV-2 (COVID-19) clade [Type] in Specimen by Molecular genetics method"
* #96764-6 "SARS-CoV-2 (COVID-19) E gene [Cycle Threshold #] in Respiratory specimen by NAA with probe detection"
* #96763-8 "SARS-CoV-2 (COVID-19) E gene [Presence] in Respiratory specimen by NAA with probe detection"
* #94562-6 "SARS-CoV-2 (COVID-19) IgA Ab [Presence] in Serum or Plasma by Immunoassay"
* #94768-9 "SARS-CoV-2 (COVID-19) IgA Ab [Presence] in Serum, Plasma or Blood by Rapid immunoassay"
* #95427-1 "SARS-CoV-2 (COVID-19) IgA Ab [Titer] in Serum or Plasma by Immunofluorescence"
* #94720-0 "SARS-CoV-2 (COVID-19) IgA Ab [Units/volume] in Serum or Plasma by Immunoassay"
* #95125-1 "SARS-CoV-2 (COVID-19) IgA+IgM [Presence] in Serum or Plasma by Immunoassay"
* #96742-2 "SARS-CoV-2 (COVID-19) IgG Ab [Mass/volume] in Serum or Plasma by Immunoassay"
* #94761-4 "SARS-CoV-2 (COVID-19) IgG Ab [Presence] in DBS by Immunoassay"
* #94563-4 "SARS-CoV-2 (COVID-19) IgG Ab [Presence] in Serum or Plasma by Immunoassay"
* #94507-1 "SARS-CoV-2 (COVID-19) IgG Ab [Presence] in Serum, Plasma or Blood by Rapid immunoassay"
* #95429-7 "SARS-CoV-2 (COVID-19) IgG Ab [Titer] in Serum or Plasma by Immunofluorescence"
* #94505-5 "SARS-CoV-2 (COVID-19) IgG Ab [Units/volume] in Serum or Plasma by Immunoassay"
* #94547-7 "SARS-CoV-2 (COVID-19) IgG+IgM Ab [Presence] in Serum or Plasma by Immunoassay"
* #95416-4 "SARS-CoV-2 (COVID-19) IgM Ab [Presence] in DBS by Immunoassay"
* #94564-2 "SARS-CoV-2 (COVID-19) IgM Ab [Presence] in Serum or Plasma by Immunoassay"
* #94508-9 "SARS-CoV-2 (COVID-19) IgM Ab [Presence] in Serum, Plasma or Blood by Rapid immunoassay"
* #95428-9 "SARS-CoV-2 (COVID-19) IgM Ab [Titer] in Serum or Plasma by Immunofluorescence"
* #94506-3 "SARS-CoV-2 (COVID-19) IgM Ab [Units/volume] in Serum or Plasma by Immunoassay"
* #96895-8 "SARS-CoV-2 (COVID-19) lineage [Identifier] in Specimen by Molecular genetics method"
* #100157-7 "SARS-CoV-2 (COVID-19) lineage [Type] in Specimen by Sequencing"
* #96957-6 "SARS-CoV-2 (COVID-19) M gene [Presence] in Upper respiratory specimen by NAA with probe detection"
* #95521-1 "SARS-CoV-2 (COVID-19) N gene [#/volume] (viral load) in Respiratory specimen by NAA with probe detection"
* #96898-2 "SARS-CoV-2 (COVID-19) N gene [Cycle Threshold #] in Oropharyngeal wash by NAA with probe detection"
* #94510-5 "SARS-CoV-2 (COVID-19) N gene [Cycle Threshold #] in Specimen by NAA with probe detection"
* #94311-8 "SARS-CoV-2 (COVID-19) N gene [Cycle Threshold #] in Specimen by Nucleic acid amplification using CDC primer-probe set N1"
* #94312-6 "SARS-CoV-2 (COVID-19) N gene [Cycle Threshold #] in Specimen by Nucleic acid amplification using CDC primer-probe set N2"
* #95522-9 "SARS-CoV-2 (COVID-19) N gene [Log #/volume] (viral load) in Respiratory specimen by NAA with probe detection"
* #94760-6 "SARS-CoV-2 (COVID-19) N gene [Presence] in Nasopharynx by NAA with probe detection"
* #96986-5 "SARS-CoV-2 (COVID-19) N gene [Presence] in Nose by NAA with non-probe detection"
* #95409-9 "SARS-CoV-2 (COVID-19) N gene [Presence] in Nose by NAA with probe detection"
* #94533-7 "SARS-CoV-2 (COVID-19) N gene [Presence] in Respiratory specimen by NAA with probe detection"
* #94756-4 "SARS-CoV-2 (COVID-19) N gene [Presence] in Respiratory specimen by Nucleic acid amplification using CDC primer-probe set N1"
* #94757-2 "SARS-CoV-2 (COVID-19) N gene [Presence] in Respiratory specimen by Nucleic acid amplification using CDC primer-probe set N2"
* #95425-5 "SARS-CoV-2 (COVID-19) N gene [Presence] in Saliva (oral fluid) by NAA with probe detection"
* #96448-6 "SARS-CoV-2 (COVID-19) N gene [Presence] in Saliva (oral fluid) by Nucleic acid amplification using CDC primer-probe set N1"
* #96958-4 "SARS-CoV-2 (COVID-19) N gene [Presence] in Saliva (oral fluid) by Nucleic acid amplification using CDC primer-probe set N2"
* #94766-3 "SARS-CoV-2 (COVID-19) N gene [Presence] in Serum or Plasma by NAA with probe detection"
* #94316-7 "SARS-CoV-2 (COVID-19) N gene [Presence] in Specimen by NAA with probe detection"
* #94307-6 "SARS-CoV-2 (COVID-19) N gene [Presence] in Specimen by Nucleic acid amplification using CDC primer-probe set N1"
* #94308-4 "SARS-CoV-2 (COVID-19) N gene [Presence] in Specimen by Nucleic acid amplification using CDC primer-probe set N2"
* #99596-9 "SARS-CoV-2 (COVID-19) N protein IgG Ab [Presence] in Serum or Plasma by Immunoassay"
* #95411-5 "SARS-CoV-2 (COVID-19) neutralizing antibody [Presence] in Serum by pVNT"
* #95410-7 "SARS-CoV-2 (COVID-19) neutralizing antibody [Titer] in Serum by pVNT"
* #97098-8 "SARS-CoV-2 (COVID-19) Nsp2 gene [Presence] in Upper respiratory specimen by NAA with probe detection"
* #98132-4 "SARS-CoV-2 (COVID-19) ORF1a region [Presence] in Respiratory specimen by NAA with probe detection"
* #98494-8 "SARS-CoV-2 (COVID-19) ORF1a region [Presence] in Saliva (oral fluid) by NAA with probe detection"
* #96899-0 "SARS-CoV-2 (COVID-19) ORF1ab region [Cycle Threshold #] in Oropharyngeal wash by NAA with probe detection"
* #94644-2 "SARS-CoV-2 (COVID-19) ORF1ab region [Cycle Threshold #] in Respiratory specimen by NAA with probe detection"
* #94511-3 "SARS-CoV-2 (COVID-19) ORF1ab region [Cycle Threshold #] in Specimen by NAA with probe detection"
* #94559-2 "SARS-CoV-2 (COVID-19) ORF1ab region [Presence] in Respiratory specimen by NAA with probe detection"
* #95824-9 "SARS-CoV-2 (COVID-19) ORF1ab region [Presence] in Saliva (oral fluid) by NAA with probe detection"
* #94639-2 "SARS-CoV-2 (COVID-19) ORF1ab region [Presence] in Specimen by NAA with probe detection"
* #97104-4 "SARS-CoV-2 (COVID-19) ORF1ab region [Units/volume] (viral load) in Upper respiratory specimen by NAA with probe detection"
* #98131-6 "SARS-CoV-2 (COVID-19) ORF1b region [Presence] in Respiratory specimen by NAA with probe detection"
* #98493-0 "SARS-CoV-2 (COVID-19) ORF1b region [Presence] in Saliva (oral fluid) by NAA with probe detection"
* #94646-7 "SARS-CoV-2 (COVID-19) RdRp gene [Cycle Threshold #] in Respiratory specimen by NAA with probe detection"
* #94645-9 "SARS-CoV-2 (COVID-19) RdRp gene [Cycle Threshold #] in Specimen by NAA with probe detection"
* #96120-1 "SARS-CoV-2 (COVID-19) RdRp gene [Presence] in Lower respiratory specimen by NAA with probe detection"
* #94534-5 "SARS-CoV-2 (COVID-19) RdRp gene [Presence] in Respiratory specimen by NAA with probe detection"
* #96091-4 "SARS-CoV-2 (COVID-19) RdRp gene [Presence] in Saliva (oral fluid) by NAA with probe detection"
* #94314-2 "SARS-CoV-2 (COVID-19) RdRp gene [Presence] in Specimen by NAA with probe detection"
* #96123-5 "SARS-CoV-2 (COVID-19) RdRp gene [Presence] in Upper respiratory specimen by NAA with probe detection"
* #99314-7 "SARS-CoV-2 (COVID-19) RdRp gene mutation detected [Identifier] in Specimen by Molecular genetics method"
* #94745-7 "SARS-CoV-2 (COVID-19) RNA [Cycle Threshold #] in Respiratory specimen by NAA with probe detection"
* #94746-5 "SARS-CoV-2 (COVID-19) RNA [Cycle Threshold #] in Specimen by NAA with probe detection"
* #94819-0 "SARS-CoV-2 (COVID-19) RNA [Log #/volume] (viral load) in Specimen by NAA with probe detection"
* #94565-9 "SARS-CoV-2 (COVID-19) RNA [Presence] in Nasopharynx by NAA with non-probe detection"
* #94759-8 "SARS-CoV-2 (COVID-19) RNA [Presence] in Nasopharynx by NAA with probe detection"
* #95406-5 "SARS-CoV-2 (COVID-19) RNA [Presence] in Nose by NAA with probe detection"
* #96797-6 "SARS-CoV-2 (COVID-19) RNA [Presence] in Oropharyngeal wash by NAA with probe detection"
* #95608-6 "SARS-CoV-2 (COVID-19) RNA [Presence] in Respiratory specimen by NAA with non-probe detection"
* #94500-6 "SARS-CoV-2 (COVID-19) RNA [Presence] in Respiratory specimen by NAA with probe detection"
* #95424-8 "SARS-CoV-2 (COVID-19) RNA [Presence] in Respiratory specimen by Sequencing"
* #94845-5 "SARS-CoV-2 (COVID-19) RNA [Presence] in Saliva (oral fluid) by NAA with probe detection"
* #94822-4 "SARS-CoV-2 (COVID-19) RNA [Presence] in Saliva (oral fluid) by Sequencing"
* #94660-8 "SARS-CoV-2 (COVID-19) RNA [Presence] in Serum or Plasma by NAA with probe detection"
* #94309-2 "SARS-CoV-2 (COVID-19) RNA [Presence] in Specimen by NAA with probe detection"
* #96829-7 "SARS-CoV-2 (COVID-19) RNA [Presence] in Specimen from Donor by NAA with probe detection"
* #96897-4 "SARS-CoV-2 (COVID-19) RNA panel - Oropharyngeal wash by NAA with probe detection"
* #94531-1 "SARS-CoV-2 (COVID-19) RNA panel - Respiratory specimen by NAA with probe detection"
* #95826-4 "SARS-CoV-2 (COVID-19) RNA panel - Saliva (oral fluid) by NAA with probe detection"
* #94306-8 "SARS-CoV-2 (COVID-19) RNA panel - Specimen by NAA with probe detection"
* #96900-6 "SARS-CoV-2 (COVID-19) S gene [Cycle Threshold #] in Oropharyngeal wash by NAA with probe detection"
* #94642-6 "SARS-CoV-2 (COVID-19) S gene [Cycle Threshold #] in Respiratory specimen by NAA with probe detection"
* #94643-4 "SARS-CoV-2 (COVID-19) S gene [Cycle Threshold #] in Specimen by NAA with probe detection"
* #94640-0 "SARS-CoV-2 (COVID-19) S gene [Presence] in Respiratory specimen by NAA with probe detection"
* #95609-4 "SARS-CoV-2 (COVID-19) S gene [Presence] in Respiratory specimen by Sequencing"
* #96765-3 "SARS-CoV-2 (COVID-19) S gene [Presence] in Saliva (oral fluid) by NAA with probe detection"
* #94767-1 "SARS-CoV-2 (COVID-19) S gene [Presence] in Serum or Plasma by NAA with probe detection"
* #94641-8 "SARS-CoV-2 (COVID-19) S gene [Presence] in Specimen by NAA with probe detection"
* #96752-1 "SARS-CoV-2 (COVID-19) S gene mutation [Presence] in Specimen by Molecular genetics method"
* #96751-3 "SARS-CoV-2 (COVID-19) S gene mutation detected [Identifier] in Specimen by Molecular genetics method"
* #99597-7 "SARS-CoV-2 (COVID-19) S protein IgG Ab [Presence] in Serum or Plasma by Immunoassay"
* #96603-6 "SARS-CoV-2 (COVID-19) S protein RBD neutralizing antibody [Presence] in Serum or Plasma by sVNT"
* #98732-1 "SARS-CoV-2 (COVID-19) S protein RBD neutralizing antibody [Titer] in Serum or Plasma by Immunoassay"
* #98734-7 "SARS-CoV-2 (COVID-19) S protein RBD neutralizing antibody [Units/volume] in Serum or Plasma by Immunoassay"
* #96894-1 "SARS-CoV-2 (COVID-19) sequencing and identification panel - Specimen by Molecular genetics method"
* #95970-0 "SARS-CoV-2 (COVID-19) specific TCRB gene rearrangements [Presence] in Blood by Sequencing"
* #100156-9 "SARS-CoV-2 (COVID-19) variant [Type] in Specimen by NAA with probe detection"
* #96741-4 "SARS-CoV-2 (COVID-19) variant [Type] in Specimen by Sequencing"
* #96755-4 "SARS-CoV-2 (COVID-19) variant interpretation in Specimen Narrative"
* #94764-8 "SARS-CoV-2 (COVID-19) whole genome [Nucleotide sequence] in Isolate or Specimen by Sequencing"
* #99772-6 "SARS-CoV-2 stimulated gamma interferon [Interpretation] in Blood Qualitative"
* #95971-8 "SARS-CoV-2 stimulated gamma interferon [Presence] in Blood"
* #95974-2 "SARS-CoV-2 stimulated gamma interferon panel - Blood"
* #95972-6 "SARS-CoV-2 stimulated gamma interferon release by T-cells [Units/volume] corrected for background in Blood"
* #95973-4 "SARS-CoV-2 stimulated gamma interferon release by T-cells [Units/volume] in Blood"
* #94509-7 "SARS-related coronavirus E gene [Cycle Threshold #] in Specimen by NAA with probe detection"
* #96121-9 "SARS-related coronavirus E gene [Presence] in Lower respiratory specimen by NAA with probe detection"
* #94758-0 "SARS-related coronavirus E gene [Presence] in Respiratory specimen by NAA with probe detection"
* #95823-1 "SARS-related coronavirus E gene [Presence] in Saliva (oral fluid) by NAA with probe detection"
* #94765-5 "SARS-related coronavirus E gene [Presence] in Serum or Plasma by NAA with probe detection"
* #94315-9 "SARS-related coronavirus E gene [Presence] in Specimen by NAA with probe detection"
* #96122-7 "SARS-related coronavirus E gene [Presence] in Upper respiratory specimen by NAA with probe detection"
* #94313-4 "SARS-related coronavirus N gene [Cycle Threshold #] in Specimen by Nucleic acid amplification using CDC primer-probe set N3"
* #94310-0 "SARS-related coronavirus N gene [Presence] in Specimen by Nucleic acid amplification using CDC primer-probe set N3"
* #94502-2 "SARS-related coronavirus RNA [Presence] in Respiratory specimen by NAA with probe detection"
* #94647-5 "SARS-related coronavirus RNA [Presence] in Specimen by NAA with probe detection"
* #94532-9 "SARS-related coronavirus+MERS coronavirus RNA [Presence] in Respiratory specimen by NAA with probe detection"
* #98062-3 "Sequencing study identifier"
* #100342-5 "Volatile Organic Compounds associated with SARS-CoV-2 infection [Presence] in Exhaled gas by Gas chromatography-mass spectrometry"
* #82593-5 "Immunization summary report"
* #11369-6 "History of Immunization Narrative"
* #30954-2 "Relevant diagnostic tests/laboratory data Narrative"
* #30980-7 "Date vaccine due"
