CodeSystem: WHODDCCicd11-mms
Title: "icd11-mms codes used in this IG"
Description: "All icd11-mms codes from `http://id.who.int/icd11/mms` used in this IG. Provided so the FHIR server can perform expansions."
* ^experimental = false
* ^caseSensitive = true
* ^url = http://id.who.int/icd11/mms

* #XM68M6 "COVID-19 vaccines"
* #XM1NL1 "COVID-19 vaccine, inactivated virus"
* #XM7HT3 "CoronaVac®"
* #XM8866 "BBIBP-CorV"
* #XM9TQ1 "KCONVAC"
* #XM1G90 "Covaxin"
* #XM85P5 "Covi-Vac"
* #XM9FQ7 "Hayat-Vax"
* #XM97N6 "Qazvac"
* #XM2YG8 "COVIran Barakat"
* #XMOK39 "Covidful"
* #XM1AU2 "Sinopharm WIBP-CorV"
* #XM5DF6 "COVID-19 vaccine, live attenuated virus"
* #XM9QW8 "COVID-19 vaccine, non-replicating viral vector"
* #XM4YL8 "COVID-19 Vaccine AstraZeneca"
* #XM97T2 "Covishield®"
* #XM6QV1 "COVID-19 Vaccine Janssen"
* #XM1AG7 "Convidecia"
* #XM5ZJ4 "Gam-Covid-Vac"
* #XM5QM6 "Sputnik-Light"
* #XMOCX4 "COVID-19 vaccine, replicating viral vector"
* #XM5JC5 "COVID-19 vaccine, virus protein subunit"
* #XM3СТ4 "Recombinant SARS-CoV-2 vaccine"
* #XM3PGO "Soberana-02"
* #XM4EC8 "MVC-COV1901"
* #XM6SZ8 "EpiVacCorona"
* #XMORV9 "Soberana Plus"
* #XM3SK8 "EpiVacCorona-N"
* #XM9P21 "SpikoGen"
* #XM9T65 "Novavax COVID-19 vaccine"
* #XM9N08 "Razi COV PARS"
* #XM1J92 "COVID-19 vaccine, virus like particle"
* #XM6AT1 "COVID-19 vaccine, DNA based"
* #XM52P3 "ZvCov-D"
* #XM0GQ8 "COVID-19 vaccine, RNA based"
* #XM8NQ0 "Comirnaty"
* #XM3DT5 "COVID-19 Vaccine Moderna"
