Alias: $eu-vmp = https://ec.europa.eu/health/documents/community-register/html/

ValueSet: VaccineEudccValueSet
Id: vaccine-covid19-euur
Title: "EU DCC COVID-19 Vaccine Medicinal Product (Union Register of medicinal products for vaccines with EU-wide authorisation)"
Description: "Union Register of medicinal products for vaccines with EU-wide authorisation. The Union Register is found at <https://ec.europa.eu/health/documents/community-register/html/index_en.htm>. However, the contents of this ValueSet are based on v1.14 (2023-01-25) of the [EU DCC value set guidelines](https://health.ec.europa.eu/system/files/2023-01/eu-dcc-value-sets_en.pdf)."

* ^copyright = "TODO: provide copyright information"

* $eu-vmp#EU/1/20/1528 "Comirnaty"
* $eu-vmp#EU/1/20/1507 "Spikevax"
* $eu-vmp#EU/1/21/1529 "Vaxzevria"
* $eu-vmp#EU/1/20/1525 "Jcovden"
* $eu-vmp#CVnCoV "CVnCoV"
* $eu-vmp#NVX-CoV2373 "NVX-CoV2373"
* $eu-vmp#Sputnik-V "Sputnik V"
* $eu-vmp#Convidecia "Convidecia"
* $eu-vmp#EpiVacCorona "EpiVacCorona"
* $eu-vmp#BBIBP-CorV "BBIBP-CorV"
* $eu-vmp#Inactivated-SARS-CoV-2-Vero-Cell "Inactivated SARS-CoV-2 (Vero Cell)"
* $eu-vmp#CoronaVac "CoronaVac"
* $eu-vmp#Covaxin "Covaxin"
* $eu-vmp#Covishield "Covishield"
* $eu-vmp#Covid-19-recombinant "Covid-19 (recombinant)"
* $eu-vmp#R-COVI "R-COVI"
* $eu-vmp#CoviVac "CoviVac"
* $eu-vmp#Sputnik-Light "Sputnik Light"
* $eu-vmp#Hayat-Vax "Hayat-Vax"
* $eu-vmp#Abdala "Abdala"
* $eu-vmp#WIBP-CorV "WIBP-CorV"
* $eu-vmp#MVC-COV1901 "MVC COVID-19 vaccine"
* $eu-vmp#EU/1/21/1618 "Nuvaxovid"
* $eu-vmp#Covovax "Covovax"
* $eu-vmp#Vidprevtyn "Vidprevtyn"
* $eu-vmp#VLA2001 "VLA2001"
* $eu-vmp#EpiVacCorona-N "EpiVacCorona- N"
* $eu-vmp#Sputnik-M "Sputnik M"
* $eu-vmp#Covid-19-adsorvida-inativada "Vacina adsorvida covid-19 (inativada)"
* $eu-vmp#NVSI-06-08 "NVSI-06-08"
* $eu-vmp#YS-SC2-010 "YS-SC2-010"
* $eu-vmp#SCTV01C "SCTV01C"
* $eu-vmp#Covifenz "Covifenz"
* $eu-vmp#AZD2816 "AZD2816"
* $eu-vmp#Soberana-02 "Soberana 02"
* $eu-vmp#Soberana-Plus "Soberana Plus"
* $eu-vmp#EU/1/21/1624 "COVID-19 Vaccine Valneva"
* $eu-vmp#EU/1/21/1580 "VidPrevtyn Beta"
