Alias: $cvx = http://hl7.org/fhir/sid/cvx

ValueSet: VaccineCovid19CvxValueSet
Id: vaccine-covid19-cvx
Title: "Vaccine - COVID-19 - Cvx"
Description: "tbd"

* ^copyright = "TODO: provide copyright information"

* $cvx#207 "COVID-19, mRNA, LNP-S, PF, 100 mcg/0.5mL dose or 50 mcg/0.25mL dose"
* $cvx#208 "COVID-19, mRNA, LNP-S, PF, 30 mcg/0.3 mL dose"
* $cvx#210 "COVID-19 vaccine, vector-nr, rS-ChAdOx1, PF, 0.5 mL "
* $cvx#211 "COVID-19, subunit, rS-nanoparticle+Matrix-M1 Adjuvant, PF, 0.5 mL"
* $cvx#212 "COVID-19 vaccine, vector-nr, rS-Ad26, PF, 0.5 mL"
* $cvx#213 "SARS-COV-2 (COVID-19) vaccine, UNSPECIFIED"
* $cvx#217 "COVID-19, mRNA, LNP-S, PF, 30 mcg/0.3 mL dose, tris-sucrose"
* $cvx#218 "COVID-19, mRNA, LNP-S, PF, 10 mcg/0.2 mL dose, tris-sucrose"
* $cvx#219 "COVID-19, mRNA, LNP-S, PF, 3 mcg/0.2 mL dose, tris-sucrose"
* $cvx#221 "COVID-19, mRNA, LNP-S, PF, 50 mcg/0.5 mL dose"
* $cvx#225 "COVID-19, D614, recomb, preS dTM, AS03 adjuvant add, PF, 5mcg/0.5mL"
* $cvx#226 "COVID-19, D614, recomb, preS dTM, AS03 adjuvant add, PF, 10mcg/0.5mL"
* $cvx#227 "COVID-19, mRNA, LNP-S, PF, pediatric 50 mcg/0.5 mL dose"
* $cvx#228 "COVID-19, mRNA, LNP-S, PF, pediatric 25 mcg/0.25 mL dose"
* $cvx#229 "COVID-19, mRNA, LNP-S, bivalent booster, PF, 50 mcg/0.5 mL or 25mcg/0.25 mL dose"
* $cvx#230 "COVID-19, mRNA, LNP-S, bivalent booster, PF, 10 mcg/0.2 mL"
* $cvx#300 "COVID-19, mRNA, LNP-S, bivalent booster, PF, 30 mcg/0.3 mL dose"
* $cvx#301 "COVID-19, mRNA, LNP-S, bivalent booster, PF, 10 mcg/0.2 mL dose"
* $cvx#302 "COVID-19, mRNA, LNP-S, bivalent, PF, 3 mcg/0.2 mL dose"
* $cvx#500 "COVID-19 Non-US Vaccine, Product Unknown"
* $cvx#501 "COVID-19 IV Non-US Vaccine (QAZCOVID-IN)"
* $cvx#502 "COVID-19 IV Non-US Vaccine (COVAXIN)"
* $cvx#503 "COVID-19 LAV Non-US Vaccine (COVIVAC)"
* $cvx#504 "COVID-19 VVnr Non-US Vaccine (Sputnik Light)"
* $cvx#505 "COVID-19 VVnr Non-US Vaccine (Sputnik V)"
* $cvx#506 "COVID-19 VVnr Non-US Vaccine (CanSino Biological Inc./Beijing Institute of Biotechnology)"
* $cvx#507 "COVID-19 PS Non-US Vaccine (Anhui Zhifei Longcom Biopharm + Inst of Micro, Chinese Acad of Sciences)"
* $cvx#508 "COVID-19 PS Non-US Vaccine (Jiangsu Province Centers for Disease Control and Prevention)"
* $cvx#509 "COVID-19 PS Non-US Vaccine (EpiVacCorona)"
* $cvx#510 "COVID-19 IV Non-US Vaccine (BIBP, Sinopharm)"
* $cvx#511 "COVID-19 IV Non-US Vaccine (CoronaVac, Sinovac)"
* $cvx#512 "SARS-COV-2 COVID-19 VLP Non-US Vaccine (Medicago, Covifenz)"
* $cvx#513 "SARS-COV-2 COVID-19 PS Non-US Vaccine (Anhui Zhifei Longcom, Zifivax)"
* $cvx#514 "SARS-COV-2 COVID-19 DNA Non-US Vaccine (Zydus Cadila, ZyCoV-D)"
* $cvx#515 "SARS-COV-2 COVID-19 PS Non-US Vaccine (Medigen, MVC-COV1901)"
* $cvx#516 "COV-2 COVID-19 Inactivated Non-US Vaccine Product (Minhai Biotechnology Co, KCONVAC)"
* $cvx#517 "SARS-COV-2 COVID-19 PS Non-US Vaccine (Biological E Limited, Corbevax)"
* $cvx#518 "COVID-19 Inactivated, Non-US Vaccine (VLA2001, Valneva)"
* $cvx#519 "COVID-19 mRNA, bivalent, original/Omicron BA.1, Non-US Vaccine (Spikevax Bivalent), Moderna"
* $cvx#520 "COVID-19 mRNA, bivalent, original/Omicron BA.1, Non-US Vaccine Product, Pfizer-BioNTech"
