Alias: $euur = https://ec.europa.eu/health/documents/community-register/html/

ValueSet: VaccineCovid19EUUnionRegisterValueSet
Id: vaccine-covid19-euur
Title: "Vaccine - COVID-19 - EU Union Register of Medicinial Products"
Description: "Union Register of medicinal products for vaccines with EU-wide authorisation. The Union Register is found at <https://ec.europa.eu/health/documents/community-register/html/index_en.htm>. However, the contents of this ValueSet are based on v1.14 (2023-01-25) of the [EU DCC value set guidelines](https://health.ec.europa.eu/system/files/2023-01/eu-dcc-value-sets_en.pdf)."

* ^experimental = true
// * ^copyright = "TODO: provide copyright information"

* $euur#EU/1/20/1528 "Comirnaty"
* $euur#EU/1/20/1507 "Spikevax"
* $euur#EU/1/21/1529 "Vaxzevria"
* $euur#EU/1/20/1525 "Jcovden"
* $euur#CVnCoV "CVnCoV"
* $euur#NVX-CoV2373 "NVX-CoV2373"
* $euur#Sputnik-V "Sputnik V"
* $euur#Convidecia "Convidecia"
* $euur#EpiVacCorona "EpiVacCorona"
* $euur#BBIBP-CorV "BBIBP-CorV"
* $euur#Inactivated-SARS-CoV-2-Vero-Cell "Inactivated SARS-CoV-2 (Vero Cell)"
* $euur#CoronaVac "CoronaVac"
* $euur#Covaxin "Covaxin"
* $euur#Covishield "Covishield"
* $euur#Covid-19-recombinant "Covid-19 (recombinant)"
* $euur#R-COVI "R-COVI"
* $euur#CoviVac "CoviVac"
* $euur#Sputnik-Light "Sputnik Light"
* $euur#Hayat-Vax "Hayat-Vax"
* $euur#Abdala "Abdala"
* $euur#WIBP-CorV "WIBP-CorV"
* $euur#MVC-COV1901 "MVC COVID-19 vaccine"
* $euur#EU/1/21/1618 "Nuvaxovid"
* $euur#Covovax "Covovax"
* $euur#Vidprevtyn "Vidprevtyn"
* $euur#VLA2001 "VLA2001"
* $euur#EpiVacCorona-N "EpiVacCorona- N"
* $euur#Sputnik-M "Sputnik M"
* $euur#Covid-19-adsorvida-inativada "Vacina adsorvida covid-19 (inativada)"
* $euur#NVSI-06-08 "NVSI-06-08"
* $euur#YS-SC2-010 "YS-SC2-010"
* $euur#SCTV01C "SCTV01C"
* $euur#Covifenz "Covifenz"
* $euur#AZD2816 "AZD2816"
* $euur#Soberana-02 "Soberana 02"
* $euur#Soberana-Plus "Soberana Plus"
* $euur#EU/1/21/1624 "COVID-19 Vaccine Valneva"
* $euur#EU/1/21/1580 "VidPrevtyn Beta"
