name: Publication Request
description: Fill out this form to create a publication-request.json file for a release
title: 'Publication Request for {version} of {package-id}'
labels: ['release', 'publication-request']
body:
  - type: dropdown
    id: mode
    attributes:
      label: Release Mode
      description: Select the mode of the release
      options:
        - working
        - milestone
        - technical-correction
        - withdrawal
  - type: dropdown
    id: status
    attributes:
      label: Release Status
      description: Select the status of this release
      options:
        - release
        - trial-use
        - update
        - preview
        - ballot
        - draft
        - normative+trial-use
        - normative
        - informative
  - type: input
    id: sequence
    attributes:
      label: Sequence Name
      description: Name of the release sequence (e.g., STU1, Release 1)
      placeholder: Enter the sequence name
  - type: textarea
    id: desc
    attributes:
      label: Description of the Release
      description: A text description of this release (optional)
      placeholder: Enter a brief description (optional)
  - type: input
    id: changes
    attributes:
      label: Link to Changes
      description: Provide a relative link to the description of changes (optional)
      placeholder: Enter the relative link to changes (optional)
  - type: checkboxes
    id: first_release
    attributes:
      label: Is this the first release?
      description: If checked, you will need to provide additional information below
      options:
        - label: Yes, this is the first release
  - type: input
    id: title
    attributes:
      label: Title (for first release only)
      description: The title of the release (only for the first release)
      placeholder: Enter the release title (only if first release)
  - type: input
    id: category
    attributes:
      label: Category (for first release only)
      description: The category of the release (only for the first release)
      placeholder: Enter the release category (only if first release)
  - type: textarea
    id: introduction
    attributes:
      label: Introduction (for first release only)
      description: A human-readable description of the intent of the IG (only for first release)
      placeholder: Enter the introduction (only if first release)
