# This workflow reuses the WHO GitHub action for building IGs
# Change log:
# v0.1.0
# 2021-06-18: publish default branches to / , other branches branches/<branch>
# 2021-11-26: reusable workflow

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for any main branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  call_build: 
    uses: WorldHealthOrganization/smart-base/.github/workflows/fhirbuild.yml@main
